
spring.datasource.url=jdbc:postgresql://localhost:5432/skill_mentor_v2
spring.datasource.username=postgres
spring.datasource.password=1234@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=a-string-secret-at-least-256-bits-long-stemlink
spring.security.user.name=skill_mentor_v2
spring.security.user.password=1234@

clerk.jwks.url=https://usable-parrot-49.clerk.accounts.dev/.well-known/jwks.json